### ISSUE TITLE
Question for yolov8

### ISSUE THREAD

**Issue by Hir98** [shubham001official/Smart-Adaptive-Traffic-Management-System#1]
@shubham001official  as you have raised question in yolov8 official repo
https://github.com/ultralytics/ultralytics/issues/2364
Have you done this to count number of object for each class??
please help me.

**Comment by shubham001official** [comment]
> 

If you're looking to utilize Yolo v8 for object detection, you can set the 'save_text' command to true in order to save the results. Following this, you can iterate through the resulting list to determine the frequency of occurrences for each class.
